apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -stage
bases:
  - ../../base
configMapGenerator:
  - name: sentinelcare-config
    behavior: merge
    literals:
      - ENVIRONMENT=stage
