apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-scoring
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: scoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: scoring
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: scoring
    spec:
      containers:
        - name: scoring
          image: "{{ .Values.global.image.repository }}/{{ .Values.image.scoring.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.scoring.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.scoring.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          ports:
            - containerPort: {{ .Values.service.scoring.port }}
          resources:
            {{- toYaml .Values.resources.scoring | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelcare.fullname" . }}-scoring
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: scoring
spec:
  selector:
    app: {{ include "sentinelcare.name" . }}
    component: scoring
  ports:
    - port: {{ .Values.service.scoring.port }}
      targetPort: {{ .Values.service.scoring.port }}
      protocol: TCP
