apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-audit
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: audit
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: audit
    spec:
      containers:
        - name: audit
          image: "{{ .Values.global.image.repository }}/{{ .Values.image.audit.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.audit.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.audit.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: MONGO_URL
              value: "mongodb://{{ .Release.Name }}-mongodb:27017"
            - name: MONGO_DB
              value: "sentinelcare"
          ports:
            - containerPort: {{ .Values.service.audit.port }}
          resources:
            {{- toYaml .Values.resources.audit | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelcare.fullname" . }}-audit
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: audit
spec:
  selector:
    app: {{ include "sentinelcare.name" . }}
    component: audit
  ports:
    - port: {{ .Values.service.audit.port }}
      targetPort: {{ .Values.service.audit.port }}
      protocol: TCP
