apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-backend
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          env:
            - name: MODEL_PATH
              value: "{{ .Values.mockModel.path }}"
            - name: ENVIRONMENT
              value: "{{ .Values.global.environment | default "dev" }}"
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelcare.fullname" . }}-backend
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: backend
spec:
  selector:
    app: {{ include "sentinelcare.name" . }}
    component: backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
      protocol: TCP
