apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-simulator
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: simulator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: simulator
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: simulator
    spec:
      containers:
        - name: simulator
          image: "{{ .Values.global.image.repository }}/{{ .Values.image.simulator.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.simulator.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.simulator.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: PATIENTS_SERVICE_URL
              value: "http://{{ include "sentinelcare.fullname" . }}-patients:{{ .Values.service.patients.port }}"
            - name: VITALS_SERVICE_URL
              value: "http://{{ include "sentinelcare.fullname" . }}-vitals:{{ .Values.service.vitals.port }}"
            - name: ALERTS_SERVICE_URL
              value: "http://{{ include "sentinelcare.fullname" . }}-alerts:{{ .Values.service.alerts.port }}"
            - name: SCORING_SERVICE_URL
              value: "http://{{ include "sentinelcare.fullname" . }}-scoring:{{ .Values.service.scoring.port }}"
            - name: SIM_INTERVAL_SECONDS
              value: "30"
          resources:
            {{- toYaml .Values.resources.simulator | nindent 12 }}
