apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-patients
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: patients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: patients
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: patients
    spec:
      containers:
        - name: patients
          image: "{{ .Values.image.patients.repository }}:{{ .Values.image.patients.tag }}"
          imagePullPolicy: {{ .Values.image.patients.pullPolicy }}
          env:
            - name: MONGO_URL
              value: "mongodb://{{ .Release.Name }}-mongodb:27017"
            - name: MONGO_DB
              value: "sentinelcare"
          ports:
            - containerPort: {{ .Values.service.patients.port }}
          resources:
            {{- toYaml .Values.resources.patients | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelcare.fullname" . }}-patients
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: patients
spec:
  selector:
    app: {{ include "sentinelcare.name" . }}
    component: patients
  ports:
    - port: {{ .Values.service.patients.port }}
      targetPort: {{ .Values.service.patients.port }}
      protocol: TCP
