apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-vitals
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: vitals
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: vitals
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: vitals
    spec:
      containers:
        - name: vitals
          image: "{{ .Values.global.image.repository }}/{{ .Values.image.vitals.repository }}:{{ .Values.image.vitals.tag | default .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.vitals.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.vitals.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: MONGO_URL
              value: "mongodb://{{ .Release.Name }}-mongodb:27017"
            - name: MONGO_DB
              value: "sentinelcare"
          ports:
            - containerPort: {{ .Values.service.vitals.port }}
          resources:
            {{- toYaml .Values.resources.vitals | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelcare.fullname" . }}-vitals
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: vitals
spec:
  selector:
    app: {{ include "sentinelcare.name" . }}
    component: vitals
  ports:
    - port: {{ .Values.service.vitals.port }}
      targetPort: {{ .Values.service.vitals.port }}
      protocol: TCP
