apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinelcare.fullname" . }}-auth
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentinelcare.name" . }}
      component: auth
  template:
    metadata:
      labels:
        app: {{ include "sentinelcare.name" . }}
        component: auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.global.image.repository }}/{{ .Values.image.auth.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.auth.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.auth.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: AUTH_SECRET
              value: "super-secret-demo-key"
            - name: AUTH_ISSUER
              value: "sentinelcare-auth"
            - name: AUTH_AUDIENCE
              value: "sentinelcare-clients"
            - name: AUTH_TOKEN_EXP_MIN
              value: "120"
          ports:
            - containerPort: {{ .Values.service.auth.port }}
          resources:
            {{- toYaml .Values.resources.auth | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelcare.fullname" . }}-auth
  labels:
    app: {{ include "sentinelcare.name" . }}
    component: auth
spec:
  selector:
    app: {{ include "sentinelcare.name" . }}
    component: auth
  ports:
    - port: {{ .Values.service.auth.port }}
      targetPort: {{ .Values.service.auth.port }}
      protocol: TCP
