apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinelcare
resources:
  - namespace.yaml
configMapGenerator:
  - name: sentinelcare-config
    literals:
      - ENVIRONMENT=dev
