apiVersion: v2
name: sentinelcare
description: SentinelCare edge-to-cloud risk scoring stack
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: mongodb
    version: 18.1.10
    repository: https://charts.bitnami.com/bitnami

